# Generated by Django 4.2.2 on 2023-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'terrible'), (2, 'bad'), (3, 'normal'), (4, 'good'), (1, 'excellent')], null=True),
        ),
    ]
